// <auto-generated />
using System;
using BackGammonDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackGammonDb.Migrations
{
    [DbContext(typeof(BacknammonContextDb))]
    [Migration("20190925070653_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Data.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTime>("Date");

                    b.Property<string>("GroupName");

                    b.Property<string>("UserName");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Common.Data.PrivateChat", b =>
                {
                    b.Property<int>("PrivateChatID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName");

                    b.Property<DateTime>("TimeCreation");

                    b.HasKey("PrivateChatID");

                    b.ToTable("PrivateChats");
                });

            modelBuilder.Entity("Common.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsOnline");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("SignalRConnectionID");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Common.Data.UserPrivateChat", b =>
                {
                    b.Property<int>("UserID");

                    b.Property<int>("PrivateChatID");

                    b.HasKey("UserID", "PrivateChatID");

                    b.HasIndex("PrivateChatID");

                    b.ToTable("UserPrivateChat");
                });

            modelBuilder.Entity("Common.Data.UserPrivateChat", b =>
                {
                    b.HasOne("Common.Data.User", "User")
                        .WithMany("UserPrivateChats")
                        .HasForeignKey("PrivateChatID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Common.Data.PrivateChat", "PrivateChat")
                        .WithMany("UserPrivateChats")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
